
version: '3.8'

services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - '5435:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
