FROM python:3.10.1
WORKDIR /app
COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the port that the application uses
EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "-w", "2",  "-k" ,"uvicorn.workers.UvicornWorker", "main:app"]
