# docker-compose.yml

version: '3.8'

services:
  web:
    container_name: FastAPI-Backend 
    build: .
    command: bash -c "
      alembic upgrade heads &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --lifespan=on --loop uvloop --http httptools --reload
      "

    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: FastPostgresDB
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - '5455:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=program

volumes:
  postgres_data:
