"""added event started at

Revision ID: b17ec9217081
Revises: f616746170c6
Create Date: 2023-11-01 06:11:26.373956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b17ec9217081"
down_revision = "f616746170c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_event", sa.Column("event_started_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calendar_event", "event_started_at")
    # ### end Alembic commands ###
