"""added repeat_until column

Revision ID: f616746170c6
Revises: c0b5f1a6999c
Create Date: 2023-10-31 23:16:02.203322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f616746170c6"
down_revision = "c0b5f1a6999c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_event", sa.Column("repeat_until", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calendar_event", "repeat_until")
    # ### end Alembic commands ###
